version: "3"
services:
  frontend-client:
    build:
      context: ./frontend-client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: always
    environment:
      - SERVER_URI=

  frontend-admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    restart: always
    environment:
      - SERVER_URI=

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    restart: always
    environment:
      - PORT=8080
      - DB_URI=
      - JWT_SECRET=
      - ADMIN_DATA=
